version: '2.1'

services:
  cassandra:
    image: cassandra:3.11
    env_file:
      - ./docker-services/cassandra/cassandra.env
    mem_limit: 4g
    memswap_limit: 4g
    mem_swappiness: 0
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
    volumes:
      - ./data/cassandra:/var/lib/cassandra
      - ./docker-services/cassandra/jmxremote.access:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management/jmxremote.access
      - ./docker-services/cassandra/jmxremote.password:/etc/cassandra/jmxremote.password

  cqlsh:
    image: cassandra:3.11
    command: cqlsh cassandra
    links:
      - cassandra

  initialize-reaper_db:
    build: ./docker-services/initialize-reaper_db
    links:
      - cassandra

  nodetool:
    image: cassandra:3.11
    entrypoint: nodetool --host cassandra --username reaperUser --password reaperPass
    links:
      - cassandra

  reaper:
    image: cassandra-reaper:latest
    env_file:
      - ./docker-services/reaper/reaper.env
    links:
      - cassandra
    ports:
      - "8080:8080"
      - "8081:8081"

  reaper-build-packages:
    extends:
      file: ./docker-build/docker-compose.yml
      service: build